CREATE TABLE ACTIVITY 
(
  ACTIVITY_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  PHASE_ID                   VARCHAR(    32) NOT NULL COLLATE UTF8,
  EMPLOYEE_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  ROLE_ID                    VARCHAR(    32) NOT NULL COLLATE UTF8,
  TYPE_ID                    VARCHAR(    32) NOT NULL COLLATE UTF8,
  ACTIVITY_DATE                 DATE         NOT NULL,
  START_TIME                    TIME,
  END_TIME                      TIME,
  STATUS                     VARCHAR(    12)  COLLATE UTF8,
 CONSTRAINT PK_ACTIVITY PRIMARY KEY (ACTIVITY_ID)
);
CREATE TABLE ACTIVITY_TYPE 
(
  TYPE_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  TYPE_NAME              VARCHAR(    20) NOT NULL COLLATE UTF8,
 CONSTRAINT PK_ACTIVITY_TYPE PRIMARY KEY (TYPE_ID)
);
CREATE TABLE CUSTOMER 
(
  CUSTOMER_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  CUSTOMER_NAME              VARCHAR(    40) NOT NULL COLLATE UTF8,
  ADDRESS                    VARCHAR(    60)  COLLATE UTF8,
  CITY                       VARCHAR(    60)  COLLATE UTF8,
  PHONE                      VARCHAR(    20)  COLLATE UTF8,
  EMAIL                      VARCHAR(    60)  COLLATE UTF8,
  STATUS                     VARCHAR(    10)  COLLATE UTF8,
 CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE EMPLOYEE 
(
  EMPLOYEE_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  EMPLOYEE_NAME              VARCHAR(    40) NOT NULL COLLATE UTF8,
  EMPLOYEE_TYPE              VARCHAR(    20)  COLLATE UTF8,
 CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);
CREATE TABLE OPERATOR_ROLE 
(
  ROLE_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  ROLE_NAME              VARCHAR(    20) NOT NULL COLLATE UTF8,
  FEE                      FLOAT,
 CONSTRAINT PK_OPERATOR_ROLE PRIMARY KEY (ROLE_ID)
);
CREATE TABLE PHASE 
(
  PHASE_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  PHASE_NAME              VARCHAR(    40) NOT NULL COLLATE UTF8,
  PROJECT_ID              VARCHAR(    32) NOT NULL COLLATE UTF8,
  START_DATE                 DATE,
  END_DATE                   DATE,
  STATUS                  VARCHAR(    12)  COLLATE UTF8,
 CONSTRAINT PK_PHASE PRIMARY KEY (PHASE_ID)
);
CREATE TABLE PROJECT 
(
  PROJECT_ID                VARCHAR(    32) NOT NULL COLLATE UTF8,
  PROJECT_NAME              VARCHAR(    40) NOT NULL COLLATE UTF8,
  CUSTOMER_ID               VARCHAR(    32) NOT NULL COLLATE UTF8,
  STATUS                    VARCHAR(    12)  COLLATE UTF8,
 CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID)
);
CREATE TABLE KITTO_USERS
(
  USER_NAME                 VARCHAR(    20) NOT NULL,
  PASSWORD_HASH             VARCHAR(    20) NOT NULL,
  IS_ACTIVE                 SMALLINT,
  FIRST_NAME                VARCHAR(    50),
  LAST_NAME                 VARCHAR(    50)
 CONSTRAINT PK_KITTO_USERS PRIMARY KEY (USER_NAME)
);



ALTER TABLE PROJECT ADD CONSTRAINT DT_PROJECT_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER
  (CUSTOMER_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE PHASE ADD CONSTRAINT DT_PHASE_PROJECT
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT
  (PROJECT_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT DT_ACTIVITY_PHASE
  FOREIGN KEY (PHASE_ID) REFERENCES PHASE
  (PHASE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_ACTIVITY_TYPE 
  FOREIGN KEY (TYPE_ID) REFERENCES ACTIVITY_TYPE
  (TYPE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_OPERATOR_ROLE 
  FOREIGN KEY (ROLE_ID) REFERENCES OPERATOR_ROLE
  (ROLE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_EMPLOYEE 
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE
  (EMPLOYEE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;



create view ACTIVITY_BY_TYPE (DURATION, TYPE_NAME)
as  
select
  avg(A.END_TIME - A.START_TIME) / 3600 DURATION,
  T.TYPE_NAME
from ACTIVITY A
join ACTIVITY_TYPE T on A.TYPE_ID = T.TYPE_ID
group by T.TYPE_NAME
;

  

ALTER TABLE ACTIVITY ADD CONSTRAINT DT_ACTIVITY_PHASE
  FOREIGN KEY (PHASE_ID) REFERENCES PHASE (PHASE_ID);
ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_ACTIVITY_TYPE
  FOREIGN KEY (TYPE_ID) REFERENCES ACTIVITY_TYPE (TYPE_ID);
ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_EMPLOYEE
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_OPERATOR_ROLE
  FOREIGN KEY (ROLE_ID) REFERENCES OPERATOR_ROLE (ROLE_ID);
ALTER TABLE PHASE ADD CONSTRAINT DT_PHASE_PROJECT
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
ALTER TABLE PROJECT ADD CONSTRAINT DT_PROJECT_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
