AppName: KEmployee2
AppTitle: Employee demo
AppIcon: FireBirdSql_120
# Default is the application name in lower case.
AppPath: /kemployee
Application:
  # When using partial proxy mode (serving /hellokitto/res/ from a separate web server)
  # you can set this to False to gain some speed. Default is True.
  HandleResources: False

# Defaults for entire application
Defaults:
  Grid:
    PageRecordCount: 100
    DefaultAction: Edit
  FormPanel:
    HideLabels: False
  Window:
    Width: 900
    Height: 500
  Layout:
    MemoWidth: 70
    MaxFieldWidth: 70
    MinFieldWidth: 6

Databases:
  Old: DBX
    Connection:
      # Example for DbExpress
      DriverName: Firebird
      DataBase: localhost:EMPLOYEE
      User_Name: SYSDBA
      Password: masterkey
      #ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False

  Main: FD
    Connection:
      # Example for FireDAC
      DriverID: FB
      Database: EMPLOYEE
      User_Name: SYSDBA
      Password: masterkey
      Server: localhost
      #CharacterSet: UTF8
      Protocol: TCPIP

Auth: TextFile
  IsPassepartoutEnabled: True
  PassepartoutPassword: password
  IsClearPassword: True
  Defaults:
    UserName: guest
    .Password: password

AccessControl: Null

Login:
  Controller:
    Title: %Config:AppTitle% %APP_VERSION%
    NorthController: HtmlPanel
      Height: 120
      Html: |
          <div style="text-align: center">
            <p/>
            <p><img src="%IMAGE(Firebird_Employee)%"></img></p>
            <p><H1>Firebird Employee Demo</H1></p>
            <p/>
          </div>
    LabelWidth: 150
    EditWidth: 200
    ExtraHeight: 100
    LocalStorage:
      Mode: Password
      AskUser: True
        .Default: False

# Change this to use a custom view for the home page.
# Alternatively, customize the Home view by replacing its controller.
# Default: Home.
#HomeView: Home

ExtJS:
  Theme: Neptune
  AjaxTimeout: 100000
# No language Id specified means try to use the language requested by the browser.
LanguageId: en
LanguagePerSession: True
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8
UserFormats:
  Date: mm/dd/yyyy
  Time: hh:nn

Log:
  # low, medium, high, detailed, debug
  Level: detailed
  TextFile:
    FileName: %APP_PATH%log.txt
    # Set this to false to disable this logger without deleting its configuration.
    IsEnabled: True

Server:
  Port: 2603
  # default 20
  ThreadPoolSize: 15

Engine:
  Session:
    # Minutes after which an inactive session is cleaned up. Defaults to 10.
    TimeOut: 10
    # Seconds after wich the cleanup of inactive sessions kicks in. Defaults to 30.
    CleanupInterval: 30

