CREATE TABLE DOLL
(
  DOLL_ID varchar(32) NOT NULL,
  DOLL_NAME varchar(40) NOT NULL,
  DATE_BOUGHT date,
  HAIR_ID varchar(32),
  DRESS_SIZE varchar(4),
  MOM_ID varchar(32) NOT NULL,
  ASPECT varchar(1024),
  PICTURE blob sub_type 0,
  CONSTRAINT PK_DOLL PRIMARY KEY (DOLL_ID)
);
CREATE TABLE GIRL
(
  GIRL_ID varchar(32) NOT NULL,
  GIRL_NAME varchar(40) NOT NULL,
  AGE integer,
  HAIR_ID varchar(32) NOT NULL,
  PHONE varchar(16),
  CONSTRAINT PK_GIRL PRIMARY KEY (GIRL_ID)
);
CREATE TABLE HAIR
(
  HAIR_ID varchar(32) NOT NULL,
  HAIR_COLOR varchar(80) NOT NULL,
  CONSTRAINT PK_HAIR PRIMARY KEY (HAIR_ID)
);
CREATE TABLE INVITATION
(
  INVITATION_ID varchar(32) NOT NULL,
  PARTY_ID varchar(32) NOT NULL,
  INVITEE_ID varchar(32) NOT NULL,
  ACCEPTED smallint,
  CONSTRAINT PK_INVITATION PRIMARY KEY (INVITATION_ID)
);
CREATE TABLE KITTO_USERS
(
  USER_NAME varchar(32) NOT NULL,
  PASSWORD_HASH varchar(32),
  IS_ACTIVE smallint,
  CONSTRAINT PK_KITTO_USERS PRIMARY KEY (USER_NAME)
);
CREATE TABLE PARTY
(
  PARTY_ID varchar(32) NOT NULL,
  PARTY_NAME varchar(40) NOT NULL,
  PARTY_DATE date NOT NULL,
  PARTY_TIME time NOT NULL,
  ADDRESS varchar(256) NOT NULL,
  CONSTRAINT PK_PARTY PRIMARY KEY (PARTY_ID)
);
/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/


ALTER TABLE DOLL ADD CONSTRAINT DT_DOLL_MOM
  FOREIGN KEY (MOM_ID) REFERENCES GIRL (GIRL_ID);
ALTER TABLE DOLL ADD CONSTRAINT FK_DOLL_HAIR
  FOREIGN KEY (HAIR_ID) REFERENCES HAIR (HAIR_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GIRL ADD CONSTRAINT FK_GIRL_HAIR
  FOREIGN KEY (HAIR_ID) REFERENCES HAIR (HAIR_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE INVITATION ADD CONSTRAINT DT_INVITATION_PARTY
  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE INVITATION ADD CONSTRAINT FK_INVITATION_GIRL
  FOREIGN KEY (INVITEE_ID) REFERENCES GIRL (GIRL_ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON DOLL TO  SYSDBA WITH GRANT OPTION;
