program KIDE2;

{$R *.dres}

uses
  {$IFDEF MADEXCEPT}
  {$ENDIF }
  MidasLib,
  EF.DB.ADO,
  EF.DB.DBX,
  Data.DBXFirebird,
  Data.DBXMSSQL,
  Data.DBXOracle,
  EF.DB.FD,
  FireDAC.Phys.MSSQL,
  FireDAC.Phys.MSSQLMeta,
  FireDAC.Phys.IBBase,
  FireDAC.Phys.IB,
  FireDAC.Phys.FB,
  FireDAC.UI.Intf,
  FireDAC.VCLUI.Wait,
  FireDAC.Stan.Intf,
  FireDAC.Comp.UI,
  System.SysUtils,
  Vcl.Forms,
  Vcl.Styles,
  Vcl.Themes,
  Kitto.Config,
  Kitto.Metadata.ModelImplementation,
  KIDE.BaseFormUnit in '..\..\Source\KIDE.BaseFormUnit.pas' {BaseForm},
  KIDE.UseKitto in '..\..\Source\KIDE.UseKitto.pas',
  MD_Label in '..\..\Ext\MDlabel\Source\MD_Label.pas',
  KIDE.HelpViewer in '..\..\Source\KIDE.HelpViewer.pas',
  DBXDevartInterBase in '..\..\Source\ThirdParty\Devart\DBXDevartInterBase.pas',
  DBXDevartSQLServer in '..\..\Source\ThirdParty\Devart\DBXDevartSQLServer.pas',
  DBXDevartOracle in '..\..\Source\ThirdParty\Devart\DBXDevartOracle.pas',
  KIDE.DbGrid in '..\..\Source\KIDE.DbGrid.pas' {BaseForm},
  KIDE.BaseWizardFormUnit in '..\..\Source\KIDE.BaseWizardFormUnit.pas' {BaseWizardForm},
  KIDE.DatabaseFrameUnit in '..\..\Source\KIDE.DatabaseFrameUnit.pas' {DatabaseFrame: TFrame},
  KIDE.DetailReferenceUpdateActionFrameUnit in '..\..\Source\KIDE.DetailReferenceUpdateActionFrameUnit.pas' {DetailReferenceUpdateActionFrame: TFrame},
  KIDE.FileTree in '..\..\Source\KIDE.FileTree.pas',
  KIDE.gettext in '..\..\Source\KIDE.gettext.pas',
  KIDE.MainFormUnit in '..\..\Source\KIDE.MainFormUnit.pas' {MainForm},
  KIDE.MetadataHelpers in '..\..\Source\KIDE.MetadataHelpers.pas',
  KIDE.ModelCreator in '..\..\Source\KIDE.ModelCreator.pas',
  KIDE.ModelUpdateActionFrameUnit in '..\..\Source\KIDE.ModelUpdateActionFrameUnit.pas' {ModelUpdateActionFrame: TFrame},
  KIDE.ModelWizardFormUnit in '..\..\Source\KIDE.ModelWizardFormUnit.pas' {ModelWizardForm},
  KIDE.MRUOptions in '..\..\Source\KIDE.MRUOptions.pas',
  KIDE.Project in '..\..\Source\KIDE.Project.pas',
  KIDE.Shell in '..\..\Source\KIDE.Shell.pas',
  KIDE.SplashFormUnit in '..\..\Source\KIDE.SplashFormUnit.pas' {SplashForm},
  KIDE.TableInfoModelUpdateActionFrameUnit in '..\..\Source\KIDE.TableInfoModelUpdateActionFrameUnit.pas' {TableInfoModelUpdateActionFrame: TFrame},
  KIDE.UpdateLocaleFormUnit in '..\..\Source\KIDE.UpdateLocaleFormUnit.pas' {UpdateLocaleForm},
  KIDE.Utils in '..\..\Source\KIDE.Utils.pas',
  KIDE.WaitFormUnit in '..\..\Source\KIDE.WaitFormUnit.pas' {WaitForm},
  KIDE.ModelFieldUpdateActionFrameUnit in '..\..\Source\KIDE.ModelFieldUpdateActionFrameUnit.pas' {ModelFieldUpdateActionFrame: TFrame},
  KIDE.ReferenceFieldUpdateActionFrameUnit in '..\..\Source\KIDE.ReferenceFieldUpdateActionFrameUnit.pas' {ReferenceFieldUpdateActionFrame: TFrame},
  KIDE.EFHelpers in '..\..\Source\KIDE.EFHelpers.pas',
  KIDE.ModelValidator in '..\..\Source\KIDE.ModelValidator.pas',
  KIDE.Process in '..\..\Source\KIDE.Process.pas',
  KIDE.ConfigValidator in '..\..\Source\KIDE.ConfigValidator.pas',
  KIDE.LayoutValidator in '..\..\Source\KIDE.LayoutValidator.pas',
  KIDE.ViewValidator in '..\..\Source\KIDE.ViewValidator.pas',
  KIDE.TreeValidator in '..\..\Source\KIDE.TreeValidator.pas',
  KIDE.DataViewWizardFormUnit in '..\..\Source\KIDE.DataViewWizardFormUnit.pas' {DataViewWizardForm},
  KIDE.Config in '..\..\Source\KIDE.Config.pas',
  KIDE.Editor in '..\..\Source\KIDE.Editor.pas',
  KIDE.Vcl.Editors in '..\..\Source\KIDE.Vcl.Editors.pas',
  KIDE.BaseFrameUnit in '..\..\Source\KIDE.BaseFrameUnit.pas' {BaseFrame: TFrame},
  KIDE.EditNodeBaseFrameUnit in '..\..\Source\KIDE.EditNodeBaseFrameUnit.pas' {EditNodeBaseFrame: TFrame},
  KIDE.EditorFrameUnit in '..\..\Source\KIDE.EditorFrameUnit.pas' {EditorFrame: TFrame},
  KIDE.ImageViewerFrameUnit in '..\..\Source\KIDE.ImageViewerFrameUnit.pas' {ImageViewerFrame: TFrame},
  KIDE.FileImageBaseFrameUnit in '..\..\Source\KIDE.FileImageBaseFrameUnit.pas' {FileImageBaseFrame: TFrame},
  KIDE.FileEditorBaseFrameUnit in '..\..\Source\KIDE.FileEditorBaseFrameUnit.pas' {FileEditorBaseFrame: TFrame},
  KIDE.TreeSearchDialogUnit in '..\..\Source\KIDE.TreeSearchDialogUnit.pas' {TreeSearchDialog: TForm},
  KIDE.SimpleNodeDesignerFrameUnit in '..\..\Source\KIDE.SimpleNodeDesignerFrameUnit.pas' {SimpleNodeDesignerFrame: TFrame},
  KIDE.TreeFolderNodeDesignerFrameUnit in '..\..\Source\KIDE.TreeFolderNodeDesignerFrameUnit.pas' {TreeFolderNodeDesignerFrame: TFrame},
  KIDE.TreeEditorBaseFrameUnit in '..\..\Source\KIDE.TreeEditorBaseFrameUnit.pas' {TreeEditorBaseFrame: TFrame},
  KIDE.MetadataEditorBaseFrameUnit in '..\..\Source\KIDE.MetadataEditorBaseFrameUnit.pas' {MetadataEditorBaseFrame: TFrame},
  KIDE.ModelEditorFrameUnit in '..\..\Source\KIDE.ModelEditorFrameUnit.pas' {ModelEditorFrame: TFrame},
  KIDE.NewProjectWizardFormUnit in '..\..\Source\KIDE.NewProjectWizardFormUnit.pas' {NewProjectWizardForm},
  KIDE.SelectOptionsFormUnit in '..\..\Source\KIDE.SelectOptionsFormUnit.pas' {SelectOptionsForm},
  KIDE.ProjectTemplate in '..\..\Source\KIDE.ProjectTemplate.pas',
  KIDE.ProjectTemplateFrameUnit in '..\..\Source\KIDE.ProjectTemplateFrameUnit.pas' {ProjectTemplateFrame: TFrame},
  KIDE.ViewEditorFrameUnit in '..\..\Source\KIDE.ViewEditorFrameUnit.pas' {ViewEditorFrame: TFrame},
  KIDE.CodeEditorFrameUnit in '..\..\Source\KIDE.CodeEditorFrameUnit.pas' {CodeEditorFrame: TFrame},
  KIDE.DesignMetadata in '..\..\Source\KIDE.DesignMetadata.pas',
  KIDE.TreeDesignerFrameUnit in '..\..\Source\KIDE.TreeDesignerFrameUnit.pas' {TreeDesignerFrame: TFrame},
  KIDE.NodeDesignerFrameUnit in '..\..\Source\KIDE.NodeDesignerFrameUnit.pas' {NodeDesignerFrame: TFrame},
  KIDE.DefaultTreeDesignerFrameUnit in '..\..\Source\KIDE.DefaultTreeDesignerFrameUnit.pas' {DefaultTreeDesignerFrame: TFrame},
  KIDE.DefaultNodeDesignerFrameUnit in '..\..\Source\KIDE.DefaultNodeDesignerFrameUnit.pas' {DefaultNodeDesignerFrame: TFrame},
  KIDE.MainDataModuleUnit in '..\..\Source\KIDE.MainDataModuleUnit.pas' {MainDataModule: TDataModule},
  KIDE.EFTreeFrameUnit in '..\..\Source\KIDE.EFTreeFrameUnit.pas' {EFTreeFrame: TFrame},
  KIDE.PersistentTreeEditorBaseFrameUnit in '..\..\Source\KIDE.PersistentTreeEditorBaseFrameUnit.pas' {PersistentTreeEditorBaseFrame: TFrame},
  KIDE.ConfigEditorFrameUnit in '..\..\Source\KIDE.ConfigEditorFrameUnit.pas' {ConfigEditorFrame: TFrame},
  KIDE.CommandDataModuleUnit in '..\..\Source\KIDE.CommandDataModuleUnit.pas' {CommandDataModule: TDataModule},
  KIDE.LayoutEditorFrameUnit in '..\..\Source\KIDE.LayoutEditorFrameUnit.pas' {LayoutEditorFrame: TFrame},
  KIDE.MetadataItemDesignerFrameUnit in '..\..\Source\KIDE.MetadataItemDesignerFrameUnit.pas' {MetadataItemDesignerFrame: TFrame},
  KIDE.ConfigDesignerFrameUnit in '..\..\Source\KIDE.ConfigDesignerFrameUnit.pas' {ConfigDesignerFrame: TFrame},
  KIDE.ConfigAuthNodeFrameUnit in '..\..\Source\KIDE.ConfigAuthNodeFrameUnit.pas' {ConfigAuthNodeFrame: TFrame},
  KIDE.ConfigDefaultsNodeFrameUnit in '..\..\Source\KIDE.ConfigDefaultsNodeFrameUnit.pas' {ConfigDefaultsNodeFrame: TFrame},
  KIDE.FormLayoutDesignerFrameUnit in '..\..\Source\KIDE.FormLayoutDesignerFrameUnit.pas' {FormLayoutDesignerFrame: TFrame},
  KIDE.GridLayoutDesignerFrameUnit in '..\..\Source\KIDE.GridLayoutDesignerFrameUnit.pas' {GridLayoutDesignerFrame: TFrame},
  KIDE.ModelFieldDesignerFrameUnit in '..\..\Source\KIDE.ModelFieldDesignerFrameUnit.pas' {ModelFieldDesignerFrame: TFrame},
  KIDE.ModelFieldsDesignerFrameUnit in '..\..\Source\KIDE.ModelFieldsDesignerFrameUnit.pas' {ModelFieldsDesignerFrame: TFrame},
  KIDE.ViewFieldsDesignerFrameUnit in '..\..\Source\KIDE.ViewFieldsDesignerFrameUnit.pas' {ViewFieldsDesignerFrame: TFrame},
  KIDE.ViewFieldDesignerFrameUnit in '..\..\Source\KIDE.ViewFieldDesignerFrameUnit.pas' {ViewFieldDesignerFrame: TFrame},
  KIDE.ViewDesignerFrameUnit in '..\..\Source\KIDE.ViewDesignerFrameUnit.pas' {ViewDesignerFrame},
  KIDE.SubViewDesignerFrameUnit in '..\..\Source\KIDE.SubViewDesignerFrameUnit.pas' {SubViewDesignerFrame},
  KIDE.ActionToolDesignerFrameUnit in '..\..\Source\KIDE.ActionToolDesignerFrameUnit.pas' {ActionToolDesignerFrame},
  KIDE.ControllerDesignerFrameUnit in '..\..\Source\KIDE.ControllerDesignerFrameUnit.pas' {ControllerDesignerFrame},
  KIDE.UploadFileToolDesignerFrameUnit in '..\..\Source\KIDE.UploadFileToolDesignerFrameUnit.pas' {UploadFileToolDesignerFrame},
  KIDE.DownloadFileToolDesignerFrameUnit in '..\..\Source\KIDE.DownloadFileToolDesignerFrameUnit.pas' {DownloadFileToolDesignerFrame},
  KIDE.SendEmailToolDesignerFrameUnit in '..\..\Source\KIDE.SendEmailToolDesignerFrameUnit.pas' {SendEmailToolDesignerFrame},
  KIDE.ReportBuilderToolDesignerFrameUnit in '..\..\Source\KIDE.ReportBuilderToolDesignerFrameUnit.pas' {ReportBuilderToolDesignerFrame},
  KIDE.PanelControllerDesignerFrameUnit in '..\..\Source\KIDE.PanelControllerDesignerFrameUnit.pas' {PanelControllerDesignerFrame},
  KIDE.ViewTableFormControllerDesignerFrameUnit in '..\..\Source\KIDE.ViewTableFormControllerDesignerFrameUnit.pas' {ViewTableFormControllerDesignerFrame},
  KIDE.ViewTableFormGridDesignerFrameUnit in '..\..\Source\KIDE.ViewTableFormGridDesignerFrameUnit.pas' {ViewTableFormGridDesignerFrame},
  KIDE.FormControllerButtonDesignerFrameUnit in '..\..\Source\KIDE.FormControllerButtonDesignerFrameUnit.pas' {FormControllerButtonDesignerFrame},
  KIDE.WindowControllerDesignerFrameUnit in '..\..\Source\KIDE.WindowControllerDesignerFrameUnit.pas' {WindowControllerDesignerFrame},
  KIDE.LoginWindowControllerDesignerFrameUnit in '..\..\Source\KIDE.LoginWindowControllerDesignerFrameUnit.pas' {LoginWindowControllerDesignerFrame},
  KIDE.LoginWindowLocalStorageDesignerFrameUnit in '..\..\Source\KIDE.LoginWindowLocalStorageDesignerFrameUnit.pas' {LoginWindowLocalStorageDesignerFrame},
  KIDE.ViewportControllerDesignerFrameUnit in '..\..\Source\KIDE.ViewportControllerDesignerFrameUnit.pas' {ViewportControllerDesignerFrame},
  KIDE.HtmlPanelControllerDesignerFrameUnit in '..\..\Source\KIDE.HtmlPanelControllerDesignerFrameUnit.pas' {HtmlPanelControllerDesignerFrame},
  KIDE.StatusBarControllerDesignerFrameUnit in '..\..\Source\KIDE.StatusBarControllerDesignerFrameUnit.pas' {StatusBarControllerDesignerFrame},
  KIDE.TabPanelControllerDesignerFrameUnit in '..\..\Source\KIDE.TabPanelControllerDesignerFrameUnit.pas' {TabPanelControllerDesignerFrame},
  KIDE.BorderPanelControllerDesignerFrameUnit in '..\..\Source\KIDE.BorderPanelControllerDesignerFrameUnit.pas' {BorderPanelControllerDesignerFrame},
  KIDE.DataPanelControllerDesignerFrameUnit in '..\..\Source\KIDE.DataPanelControllerDesignerFrameUnit.pas' {DataPanelControllerDesignerFrame},
  KIDE.FormPanelControllerDesignerFrameUnit in '..\..\Source\KIDE.FormPanelControllerDesignerFrameUnit.pas' {FormPanelControllerDesignerFrame},
  KIDE.ListPanelControllerDesignerFrameUnit in '..\..\Source\KIDE.ListPanelControllerDesignerFrameUnit.pas' {ListPanelControllerDesignerFrame},
  KIDE.GridPanelControllerDesignerFrameUnit in '..\..\Source\KIDE.GridPanelControllerDesignerFrameUnit.pas' {GridPanelControllerDesignerFrame},
  KIDE.DataToolDesignerFrameUnit in '..\..\Source\KIDE.DataToolDesignerFrameUnit.pas' {DataToolDesignerFrame},
  KIDE.LogoutDesignerFrameUnit in '..\..\Source\KIDE.LogoutDesignerFrameUnit.pas' {LogoutDesignerFrame},
  KIDE.ToolDesignerFrameUnit in '..\..\Source\KIDE.ToolDesignerFrameUnit.pas' {ToolDesignerFrame},
  KIDE.ExportExcelToolDesignerFrameUnit in '..\..\Source\KIDE.ExportExcelToolDesignerFrameUnit.pas' {ExportExcelToolDesignerFrame},
  KIDE.UploadExcelToolDesignerFrameUnit in '..\..\Source\KIDE.UploadExcelToolDesignerFrameUnit.pas' {UploadExcelToolDesignerFrame},
  KIDE.MergePDFToolDesignerFrameUnit in '..\..\Source\KIDE.MergePDFToolDesignerFrameUnit.pas' {MergePDFToolDesignerFrame},
  KIDE.FOPToolDesignerFrameUnit in '..\..\Source\KIDE.FOPToolDesignerFrameUnit.pas' {FOPToolDesignerFrame},
  KIDE.ExportTextToolDesignerFrameUnit in '..\..\Source\KIDE.ExportTextToolDesignerFrameUnit.pas' {ExportTextToolDesignerFrame},
  KIDE.PairsValuesFrameUnit in '..\..\Source\KIDE.PairsValuesFrameUnit.pas' {PairsValuesFrame: TFrame},
  KIDE.PreviewLayoutForm in '..\..\Source\KIDE.PreviewLayoutForm.pas' {PreviewLayoutForm},
  KIDE.ModelDesignerFrameUnit in '..\..\Source\KIDE.ModelDesignerFrameUnit.pas' {ModelDesignerFrame: TFrame},
  KIDE.ConfigAccessControlNodeFrameUnit in '..\..\Source\KIDE.ConfigAccessControlNodeFrameUnit.pas' {ConfigAccessControlNodeFrame: TFrame},
  KIDE.ConfigDatabasesNodeFrameUnit in '..\..\Source\KIDE.ConfigDatabasesNodeFrameUnit.pas' {ConfigDatabasesNodeFrame: TFrame},
  KIDE.ConnectionFrameUnit in '..\..\Source\KIDE.ConnectionFrameUnit.pas' {ConnectionFrame: TFrame},
  KIDE.DatabaseNodeFrameUnit in '..\..\Source\KIDE.DatabaseNodeFrameUnit.pas' {DatabaseNodeFrame: TFrame},
  KIDE.ModelRulesNodeFrameUnit in '..\..\Source\KIDE.ModelRulesNodeFrameUnit.pas' {ModelRulesNodeFrame: TFrame},
  KIDE.RuleNodeFrameUnit in '..\..\Source\KIDE.RuleNodeFrameUnit.pas' {RuleNodeFrame: TFrame},
  KIDE.SendEmailDestinationNodeFrameUnit in '..\..\Source\KIDE.SendEmailDestinationNodeFrameUnit.pas' {SendEmailDestinationNodeFrame: TFrame},
  KIDE.SendEmailMessageNodeFrameUnit in '..\..\Source\KIDE.SendEmailMessageNodeFrameUnit.pas' {SendEmailMessageNodeFrame: TFrame},
  KIDE.ConfigEmailSMTPNodeFrameUnit in '..\..\Source\KIDE.ConfigEmailSMTPNodeFrameUnit.pas' {ConfigEmailSMTPNodeFrame: TFrame},
  KIDE.ConfigEmailNodeFrameUnit in '..\..\Source\KIDE.ConfigEmailNodeFrameUnit.pas' {ConfigEmailNodeFrame: TFrame},
  KIDE.ConfigEmailSMTPServerNodeFrameUnit in '..\..\Source\KIDE.ConfigEmailSMTPServerNodeFrameUnit.pas' {ConfigEmailSMTPServerNodeFrame: TFrame},
  KIDE.ListControllerFiltersNodeFrameUnit in '..\..\Source\KIDE.ListControllerFiltersNodeFrameUnit.pas' {ListControllerFiltersNodeFrame: TFrame},
  KIDE.ListControllerFiltersItemsNodeFrameUnit in '..\..\Source\KIDE.ListControllerFiltersItemsNodeFrameUnit.pas' {ListControllerFiltersItemsNodeFrame: TFrame},
  KIDE.ListControllerListFilterBaseNodeFrameUnit in '..\..\Source\KIDE.ListControllerListFilterBaseNodeFrameUnit.pas' {ListControllerListFilterBaseNodeFrame: TFrame},
  KIDE.ListControllerButtonListFilterBaseNodeFrameUnit in '..\..\Source\KIDE.ListControllerButtonListFilterBaseNodeFrameUnit.pas' {ListControllerButtonListFilterBaseNodeFrame: TFrame},
  KIDE.ListControllerListFilterNodeFrameUnit in '..\..\Source\KIDE.ListControllerListFilterNodeFrameUnit.pas' {ListControllerListFilterNodeFrame: TFrame},
  KIDE.ListControllerButtonListFilterNodeFrameUnit in '..\..\Source\KIDE.ListControllerButtonListFilterNodeFrameUnit.pas' {ListControllerButtonListFilterNodeFrame: TFrame},
  KIDE.ListControllerDynaListFilterNodeFrameUnit in '..\..\Source\KIDE.ListControllerDynaListFilterNodeFrameUnit.pas' {ListControllerDynaListFilterNodeFrame: TFrame},
  KIDE.ListControllerDynaButtonListFilterNodeFrameUnit in '..\..\Source\KIDE.ListControllerDynaButtonListFilterNodeFrameUnit.pas' {ListControllerDynaButtonListFilterNodeFrame: TFrame},
  KIDE.ListControllerListFilterItemsFrameUnit in '..\..\Source\KIDE.ListControllerListFilterItemsFrameUnit.pas' {ListControllerListFilterItemsFrame: TFrame},
  KIDE.ListControllerButtonListFilterItemsFrameUnit in '..\..\Source\KIDE.ListControllerButtonListFilterItemsFrameUnit.pas' {ListControllerButtonListFilterItemsFrame: TFrame},
  KIDE.ViewTableControllerToolViewsFrameUnit in '..\..\Source\KIDE.ViewTableControllerToolViewsFrameUnit.pas' {ViewTableControllerToolViewsFrame: TFrame},
  KIDE.ListControllerListFilterItemFrameUnit in '..\..\Source\KIDE.ListControllerListFilterItemFrameUnit.pas' {ListControllerListFilterItemFrame: TFrame},
  KIDE.ListControllerButtonListFilterItemFrameUnit in '..\..\Source\KIDE.ListControllerButtonListFilterItemFrameUnit.pas' {ListControllerButtonListFilterItemFrame: TFrame},
  KIDE.ListControllerFilterItemFrameUnit in '..\..\Source\KIDE.ListControllerFilterItemFrameUnit.pas' {ListControllerFilterItemFrame: TFrame},
  KIDE.ListControllerFilterColumnBreakFrameUnit in '..\..\Source\KIDE.ListControllerFilterColumnBreakFrameUnit.pas' {ListControllerFilterColumnBreakFrame: TFrame},
  KIDE.ListControllerFilterSpacerFrameUnit in '..\..\Source\KIDE.ListControllerFilterSpacerFrameUnit.pas' {ListControllerFilterSpacerFrame: TFrame},
  KIDE.ListControllerFilterApplyButtonFrameUnit in '..\..\Source\KIDE.ListControllerFilterApplyButtonFrameUnit.pas' {ListControllerFilterApplyButtonFrame: TFrame},
  KIDE.ViewTableDesignerFrameUnit in '..\..\Source\KIDE.ViewTableDesignerFrameUnit.pas' {ViewTableDesignerFrame: TFrame},
  KIDE.ViewDetailTablesDesignerFrameUnit in '..\..\Source\KIDE.ViewDetailTablesDesignerFrameUnit.pas' {ViewDetailTablesDesignerFrame: TFrame},
  KIDE.MainTableControllerDesignerFrameUnit in '..\..\Source\KIDE.MainTableControllerDesignerFrameUnit.pas' {MainTableControllerDesignerFrame: TFrame},
  KIDE.MainTableControllerGroupingDesignerFrameUnit in '..\..\Source\KIDE.MainTableControllerGroupingDesignerFrameUnit.pas' {MainTableControllerGroupingDesignerFrame: TFrame},
  KIDE.DataViewDesignerFrameUnit in '..\..\Source\KIDE.DataViewDesignerFrameUnit.pas' {DataViewDesignerFrame: TFrame},
  KIDE.TreeViewDesignerFrameUnit in '..\..\Source\KIDE.TreeViewDesignerFrameUnit.pas' {TreeViewDesignerFrame: TFrame},
  KIDE.LoginViewDesignerFrameUnit in '..\..\Source\KIDE.LoginViewDesignerFrameUnit.pas' {LoginViewDesignerFrame: TFrame},
  KIDE.MobileSettingsDesignerFrameUnit in '..\..\Source\KIDE.MobileSettingsDesignerFrameUnit.pas' {MobileSettingsDesginerFrame: TFrame};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TMainDataModule, MainDataModule);
  Application.MainFormOnTaskbar := True;
  Application.Title := 'KIDE2';
{$IFDEF MADEXCEPT}
  RegisterExceptionHandler(MainDataModule.ShowMadExcept, stTrySyncCallOnSuccess);
{$ENDIF}
  SplashForm := TSplashForm.Create(nil);
  try
    if not FindCmdLineSwitch('nosplash') then
    begin
      SplashForm.Show;
      SplashForm.Update;
    end;
  Application.CreateForm(TMainForm, MainForm);
  if not FindCmdLineSwitch('nosplash') then
      Sleep(500);
  finally
    FreeAndNil(SplashForm);
  end;
  Application.Run;
end.
